version: '3'
services:
  postgres_db44:
    image: postgres:14-alpine
    container_name: "postgres44"
    environment:
      - "POSTGRES_PASSWORD=SecretPassword123"
      - "POSTGRES_DB=hazel_mtzdb"
      - "POSTGRES_USER=hazel_mtz"
    ports:
      - "10044:5544"
    volumes:
      - "/home/hazel_mtz/postgres:/usr/src/postgres"
    networks:
      - our-library-net
    command: -p 5544

  web44:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && pytest && python manage.py runserver 0.0.0.0:8044"
    container_name: "django44"
    depends_on: 
      - postgres_db44
    environment:
      - "PSQL_DBNAME=hazel_mtzdb"
      - "PSQL_USERNAME=hazel_mtz"
      - "PSQL_PASS=SecretPassword123"
      - "PSQL_HOST=172.24.0.9" # You must use the previous command in order to get this HOST
      - "PSQL_PORT=5544"
    volumes:
    # "RUTA/DEL/SERVIDOR:RUTA/DENTRO/DEL/CONTENEDOR"
      - "/home/hazel_mtz/django/library:/usr/src/django/library"
    ports:
      - "9044:8044"
    networks:
      - our-library-net
networks:
  our-library-net:
    external: true
    driver: bridge