name: Django Test with PostgreSQL Example

on:
    workflow_call:
    workflow_dispatch:
    push:
       branches: [main, pytest]
    pull_request:
        branches: [main, pytest]
jobs:
  simple_build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: pytest # Checkout with pytest branch
#      - name: Install docker
#        uses: docker/setup-buildx-action@v1.6
#        id: buildx
#        with:
#          install: true
      - name: Install docker compose   
        uses: KengoTODA/actions-setup-docker-compose@main
        with: 
          version: '3' # Version of docker compose
      - name: Build django image
        run: |
            docker build -t my-django-image44:2.0.0 .
      - name: Run docker containers
        run: |
            docker-compose up --build -d